version: '2'

services:
  node:
    build:
      context: .
      dockerfile: node.dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge
